"""M0 runtime boundaries for event/evidence storage, work repositories, and steps."""

from curios_runtime.agent_lifecycle_repository import (
    AGENT_INSTANCE_TRANSITIONS,
    AGENT_LIFECYCLE_EVENT_TYPE,
    AgentLifecycleError,
    AgentLifecycleErrorCode,
    M1AgentLifecycleRepository,
    StoredAgentLifecycleTransition,
    agent_lifecycle_event,
    transition_agent_instance,
)
from curios_runtime.agent_repository import (
    AgentRepositoryError,
    AgentRepositoryErrorCode,
    M1AgentRepository,
    StoredAgentDefinition,
    StoredAgentInstance,
)
from curios_runtime.event_evidence_store import (
    EventEvidenceRuntimeStore,
    RuntimeStoreError,
    RuntimeStoreErrorCode,
)
from curios_runtime.executor_seam import (
    M1_EXECUTOR_EVENT_TYPE,
    DeterministicM1Executor,
    ExecutorErrorCode,
    ExecutorOutcome,
    ExecutorOutcomeStatus,
    ExecutorRequest,
    M1Executor,
)
from curios_runtime.m1_bounded_dag_runner import (
    BoundedM1DagRunner,
    M1DagRunnerError,
    M1DagRunnerErrorCode,
    M1DagRunnerNodeResult,
    M1DagRunnerNodeStatus,
    M1DagRunnerReasonCode,
    M1DagRunnerRequest,
    M1DagRunnerResult,
    M1DagRunnerStatus,
)
from curios_runtime.provider_inventory_executor import ProviderInventoryExecutor
from curios_runtime.routing_decision_repository import (
    M1RoutingDecisionRepository,
    RouteCandidateKind,
    RoutingCandidate,
    RoutingDecisionError,
    RoutingDecisionErrorCode,
    RoutingDecisionRationale,
    RoutingDecisionRecord,
    RoutingDecisionRequest,
    RoutingDecisionStatus,
    RoutingRationaleCode,
    StoredRoutingDecision,
    select_m1_route,
)
from curios_runtime.single_step_runtime import (
    SingleStepExecutionOutcome,
    SingleStepExecutionRequest,
    SingleStepExecutor,
    SingleStepRuntimeError,
    SingleStepRuntimeErrorCode,
    SingleStepRuntimeRequest,
    SingleStepRuntimeResult,
    SingleStepRuntimeService,
    SingleStepRuntimeStatus,
)
from curios_runtime.work_repository import (
    EXECUTION_TRANSITIONS,
    WORK_ITEM_TRANSITIONS,
    M0WorkRepository,
    RepositoryError,
    RepositoryErrorCode,
    StoredExecutionRecord,
    StoredWorkItem,
    transition_execution_record,
    transition_work_item,
)

__version__ = "0.0.0"

__all__ = (
    "AGENT_INSTANCE_TRANSITIONS",
    "AGENT_LIFECYCLE_EVENT_TYPE",
    "EXECUTION_TRANSITIONS",
    "WORK_ITEM_TRANSITIONS",
    "AgentLifecycleError",
    "AgentLifecycleErrorCode",
    "AgentRepositoryError",
    "AgentRepositoryErrorCode",
    "EventEvidenceRuntimeStore",
    "M1_EXECUTOR_EVENT_TYPE",
    "BoundedM1DagRunner",
    "DeterministicM1Executor",
    "ExecutorErrorCode",
    "ExecutorOutcome",
    "ExecutorOutcomeStatus",
    "ExecutorRequest",
    "M1DagRunnerError",
    "M1DagRunnerErrorCode",
    "M1DagRunnerNodeResult",
    "M1DagRunnerNodeStatus",
    "M1DagRunnerReasonCode",
    "M1DagRunnerRequest",
    "M1DagRunnerResult",
    "M1DagRunnerStatus",
    "M1AgentLifecycleRepository",
    "M0WorkRepository",
    "M1AgentRepository",
    "M1Executor",
    "ProviderInventoryExecutor",
    "RepositoryError",
    "RepositoryErrorCode",
    "M1RoutingDecisionRepository",
    "RouteCandidateKind",
    "RoutingCandidate",
    "RoutingDecisionError",
    "RoutingDecisionErrorCode",
    "RoutingDecisionRationale",
    "RoutingDecisionRecord",
    "RoutingDecisionRequest",
    "RoutingDecisionStatus",
    "RoutingRationaleCode",
    "RuntimeStoreError",
    "RuntimeStoreErrorCode",
    "SingleStepExecutionOutcome",
    "SingleStepExecutionRequest",
    "SingleStepExecutor",
    "SingleStepRuntimeError",
    "SingleStepRuntimeErrorCode",
    "SingleStepRuntimeRequest",
    "SingleStepRuntimeResult",
    "SingleStepRuntimeService",
    "SingleStepRuntimeStatus",
    "StoredAgentLifecycleTransition",
    "StoredAgentDefinition",
    "StoredAgentInstance",
    "StoredExecutionRecord",
    "StoredRoutingDecision",
    "StoredWorkItem",
    "__version__",
    "agent_lifecycle_event",
    "transition_agent_instance",
    "transition_execution_record",
    "transition_work_item",
    "select_m1_route",
)
